const express = require('express');
const apiController = require(__dirname+'/../controllers/api/');

const router = new express.Router();

router.get('/v1/payments/incoming', apiController.listIncomingPayments);
router.post('/v1/payments/outgoing', apiController.enqueueOutgoingPayment);
router.get('/v1/payments/outgoing', apiController.listOutgoingPayments);
router.get('/v1/payments/failed', apiController.listFailedPayments);
router.post('/v1/payments/failed/:id/retry', apiController.retryFailedPayment);
router.get('/v1/withdrawals', apiController.listQueuedWithdrawals);
router.post('/v1/withdrawals/:id/clear', apiController.clearWithdrawal);
router.post('/v1/wallets/hot/fund', apiController.fundHotWallet);
router.post('/v1/deposits', apiController.recordDeposit);
router.get('/v1/deposits', apiController.listQueuedDeposits);
router.get('/v1/cleared', apiController.listCleared);
router.get('/v1/users/:id/external_accounts', apiController.listUserExternalAccounts);
router.post('/v1/users/:id/activate', apiController.activateUser);
router.post('/v1/users/:id/deactivate', apiController.deactivateUser);
router.post('/v1/registrations', apiController.registerUser);
router.post('/v1/start', apiController.startGateway);
router.get('/v1/config/database', apiController.getDatabaseUrl);
router.post('/v1/config/database', apiController.setDatabaseUrl);
router.get('/v1/config/ripple/rest', apiController.getRippleRestUrl);
router.post('/v1/config/ripple/rest', apiController.setRippleRestUrl);
router.get('/v1/config/domain', apiController.getDomain);
router.post('/v1/config/domain', apiController.setDomain);
router.post('/v1/wallets/generate', apiController.generateWallet);
router.post('/v1/config/wallets/hot', apiController.setHotWallet);
router.get('/v1/config/wallets/hot', apiController.getHotWallet);
router.post('/v1/config/wallets/cold', apiController.setColdWallet);
router.get('/v1/config/wallets/cold', apiController.getColdWallet);
router.post('/v1/wallets/hot/fund', apiController.fundHotWallet);
router.get('/v1/config/key', apiController.getKey);
router.post('/v1/config/key', apiController.setKey);
router.get('/v1/currencies', apiController.listCurrencies);
router.post('/v1/currencies', apiController.addCurrency);
router.delete('/v1/currencies/:currency', apiController.removeCurrency);
router.post('/v1/trust', apiController.setTrustLine);
router.get('/v1/trust', apiController.getTrustLines);
router.post('/v1/config/last_payment_hash', apiController.setLastPaymentHash);
router.get('/v1/config/last_payment_hash', apiController.getLastPaymentHash);
router.post('/v1/wallets/cold/refund', apiController.refundColdWallet);
router.get('/v1/processes', apiController.listProcesses);
router.get('/v1/balances', apiController.getAccountBalance);
router.get('/v1/liabilities', apiController.getLiabilities);
router.get('/v1/trustlines/:account', apiController.listTrustlines);

module.exports = router;

